require "common.rb"

class << self

  # new_entry -- Introduce a new entry for the Makefile.
  def new_entry a_string
    puts
    puts a_string
  end

  # tab -- Output a line preceded by a tab character, to mean
  # what indentation means in a Makefile.
  def tab a_string
    print "\t"
    puts a_string
  end

  def debug line, description, value
    return
    puts
    print "# "
    print line.inspect
    print " "
    print description
    print ": "
    puts value.inspect
    puts
  end

  def commit
    tab "mv $@.t $@"
  end

  # Procedure to output a simple Ruby dependency in the Makefile.
  def simple_ruby_dep name, *other_deps
    debug __LINE__, "other_deps", other_deps
    other_deps_string = other_deps.inject("") do | a, e |
      debug __LINE__, "a", a
      debug __LINE__, "e", e
      a + " " + e
    end
    new_entry "../public/#{name}: #{name}.rb#{other_deps_string}"
    tab "ruby $(RUBYOPT) #{name}.rb >$@.t"
    commit
  end

  # Generate a local Ruby dependency.
  def local_ruby_dep name, *other_deps
    other_deps_string = other_deps.inject("") do | a, e |
      a + " " + e
    end
    new_entry "#{name}: #{name}.rb#{other_deps_string}"
    tab "ruby $(RUBYOPT) #{name}.rb >$@.t"
    commit
  end

end

specified_tgts = [
  "style.css",
  "index.html",
]

images = filenames_in_dir_named "images"
tgt_images = images.map {|e| "img/#{e}"}
articles_dirs_names = ["our_articles", "others_articles"]
other_public_dirs = [ "img",
]
tgt_dirs = ["../public"] +
  ((other_public_dirs + articles_dirs_names).
    map {|e| "../public/#{e}"})
articles_rubyless_names = []
articles_dirs_names.each do |n|
  articles_rubyless_names += filenames_in_dir_named(n).map do |e|
    "#{n}/#{e}".sub(/\.rb\Z/, "")
  end
end
tgt_articles = articles_rubyless_names

tgts = specified_tgts + tgt_images + tgt_articles
tgts_string = tgts.inject("") do | a, e |
  a + " ../public/" + e
end
tgt_dirs_string = tgt_dirs.inject("") do | a, e |
  a + " " + e
end

puts "# Generated by #{__FILE__}."
puts
puts "RUBYOPT = -I."



# The next entry is normally the first in the Makefile, so
# that making these targets is the default thing to do when
# you type "make".

new_entry "tgts:#{tgt_dirs_string} #{tgts_string}"
tab "ruby $(RUBYOPT) tell_photo_width.rb"



new_entry "list: . left right our_articles others_articles"
tab "ls *.rb >$@.t"
%w(left right our_articles others_articles).each do |e|
  tab "ls #{e}/*.rb >>$@.t"
end
commit

new_entry "try: tgts"
tab "firefox ../public/index.html >/dev/null 2>&1&"

new_entry "clean:"
tab "rm -f *~ ../public/*.t */*~"

new_entry "pristeen: clean"
tab "rm -rf ../public"

tgt_dirs.each do |e|
  new_entry "#{e}:"
  tab "test -d $@ || mkdir $@"
end

simple_ruby_dep "style.css", "common.rb", "env.rb"
simple_ruby_dep "index.html", "common.rb", "left", "right",
  "left/*", "right/*", "env.rb"

articles_rubyless_names.each do |e|
  simple_ruby_dep e, "common.rb", "env.rb"
end

local_ruby_dep "Makefile", "common.rb", "images",
  "*articles*", "env.rb"

images.each do |i|
  new_entry "../public/img/#{i}: images/#{i}"
  tab "rm -f $@"
  tab "ln $? $@"
end

